### ISSUE TITLE
[BUG]  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bookstack.users' doesn't exist in /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php:414

### ISSUE THREAD

**Issue by xigyou** [linuxserver/docker-bookstack#192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

start docker and visit http://localhost:6875  it's blank
and check the log.

### Steps To Reproduce

docker run -d \
  --name=bookstack\
  -e PUID=501\
  -e PGID=20\
  -e TZ=[Asia/Shanghai](https://en.wikipedia.org/wiki/Asia/Shanghai)\
  -e APP_URL=http://localhost:6875/\
  -e DB_HOST=192.8.8.15\
  -e DB_PORT=3306\
  -e DB_USER=bookstack\
  -e DB_PASS=passwd\
  -e DB_DATABASE=bookstack\
  -e QUEUE_CONNECTION=database\
  -p 6875:80 \
  -v /Volumes/Data/bookstack_data:/config \
  --restart unless-stopped \
  linuxserver/bookstack:23.08.3

### CPU architecture

x86-64

### Docker creation

```bash
docker pull linuxserver/bookstack:23.08.3
```

### Container logs

```bash
tail -n 100 log/nginx/error.log

2023/10/17 15:43:02 [error] 318#318: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bookstack.users' doesn't exist in /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php:414
Stack trace:
#0 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(414): PDO->prepare()
#1 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(753): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#2 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(720): Illuminate\Database\Connection->runQueryCallback()
#3 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(405): Illuminate\Database\Connection->run()
#4 /app/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2705): Illuminate\Database\Connection->select()
#5 /app/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2694): Illuminate\Database\Query\Builder->runSelect()
#6 /app/www/vendor/...; PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bookstack.users' doesn't exist in /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php:414
Stack trace:
#0 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(414): PDO->prepare()
#1 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(753): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#2 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(720): Illuminate\Database\Connection->runQueryCallback()
#3 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(405): Illuminate\Database\Connection->run()
#4 /app/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2705): Illuminate\Database\Connection->select()
#5 /app/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2694): Illuminate\Database
```

**Comment by xigyou** [comment]
mac@macdeMacBook-Pro ~ % docker exec -it bookstack /bin/bash
root@f04582d10d5b:/app/www# php artisan migrate
